# Generated by Django 5.0.6 on 2024-06-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dating', '0002_user_age_user_dob_user_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
